// front-end-react/src/components/Navbar.js
import React from 'react'

const Navbar = () => {
    return (
        <nav class="navbar navbar-expand-md navbar-dark fixed-top">
            <div class='container'>
                <a class="navbar-brand">
                    <img src='favicon.ico' width="50" height="50" class="d-inline-block align-top" alt="" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link">Your Apps</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link">Register</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link">Logout</a>
                        </li>
                    </ul >
                </div >
            </div >
        </nav >
    )
}
export default Navbar

// front-end-angular/src/app/components/layout/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { UserService } from '../../../user.service'

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  constructor(
    private _Router: Router, private _UserService: UserService) { }

  ngOnInit() { }

  get loginStatus() {
    return this._UserService.loginStatus
  }

  logoutUser() {
    this._UserService.logoutUser().subscribe(data => {
      if (data.success) {
        this._UserService.setLoginStatus(false)
        this._Router.navigate([''])
      }
      else {
        window.alert('Could not logout.')
      }
    })
  }

}

<nav class="navbar navbar-expand-md navbar-dark fixed-top">
    <div class='container'>
        <a class="navbar-brand" routerLink=''>
            <img src='favicon.ico' width="50" height="50" class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" routerLink='' routerLinkActive="active">Home</a>
                </li>
                <li class="nav-item" *ngIf='loginStatus'>
                    <a class="nav-link" routerLink='apps' routerLinkActive="active">Your Apps</a>
                </li>
            </ul>
            <ul class="navbar-nav" *ngIf='!loginStatus'>
                <li class="nav-item">
                    <a class="nav-link" routerLink='login' routerLinkActive="active">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" routerLink='registerUser' routerLinkActive="active">Register</a>
                </li>
            </ul>
            <ul class="navbar-nav" *ngIf="loginStatus">
                <li class="nav-item">
                    <a class="nav-link" (click)='logoutUser()'>Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
