// front-end-react/src/components/Apps.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom'
import axios from 'axios';

class Apps extends Component {
    constructor(props) {
        super(props)
        this.state = {
            apps: [],
            errMessage: ''
        }
    }

    componentDidMount() {
        axios.get('http://localhost:5000/apps', { withCredentials: true })
            .then(response => {
                this.setState({ apps: response.data })
            })
            .catch(error => {
                console.log(error)
                this.setState({ errMessage: 'Error retreiving data.' })
            });
    }

    render() {
        const { apps, errMessage } = this.state
        return (
            <div>
                <div className='row'>
                    <h1 className='col-6'>Apps</h1>
                    <div className='col-6'>
                        <Link to='blank' className='btn btn-primary btn-lg float-right'>Register App</Link>
                    </div>
                    {
                        errMessage ? <div className='col-12'>{errMessage}</div> : null
                    }
                    {
                        apps.length ?
                            apps.map(app =>
                                <div key={app.key} className='col-12 mt-3 mb-3 app'>
                                    <div className='card bg-dark'>
                                        <div className='card-body'>
                                            <h2 className='d-inline'>{app.name}</h2>
                                            <div className='float-right'>
                                                <Link to='thermostats' className='btn btn-info'>View</Link>
                                                <Link to='blank' className='btn btn-info'>Reauthorize</Link>
                                                <Link to='blank' className='btn btn-info'>Update App Credentials</Link>
                                                <button className='btn btn-danger'>Delete</button>
                                            </div>
                                        </div>
                                    </div>
                                </div >
                            ) :
                            <div className='col-12 mt-3 mb-3'>
                                You currently have no apps registered with this account.
                        </div>

                    }
                </div>

            </div >

        );
    }
}

export default Apps;

// front-end/src/app/components/apps/apps.component.ts
import { Component, OnInit } from '@angular/core';
import { APIService } from '../../api.service'
import { Router } from '@angular/router';

@Component({
  selector: 'app-apps',
  templateUrl: './apps.component.html',
  styleUrls: ['./apps.component.css']
})
export class AppsComponent implements OnInit {

  public apis = [];

  constructor(private _APIService: APIService,
              private _router: Router) { }

  ngOnInit() {
    this._APIService.getAPIS()
    .subscribe(data => {this.apis = data; console.log(data)})
  }

  onSelect(key){
    this._router.navigate(['/apps', key])
  }

  deleteAPI(key){
    this._APIService.deleteAPI(key)
  }

}

<h1>APIs</h1>
<div class='row'>
    <div class='col-12 mt-3 mb-3 app' *ngFor='let api of apis'>
        <div class='card bg-dark'>
            <div class='card-body'>
                <h2 class='d-inline'>{{api.name}}</h2>
                <div class='float-right'>
                    <a (click)='onSelect(api.key)' class='btn btn-info'>View</a>
                    <button class='btn btn-success'>Edit</button>
                    <button (click)='deleteAPI(api.key)' class='btn btn-danger'>Delete</button>
                </div>
            </div>
        </div>
    </div>
</div>
