// front-end-react/src/components/RegisterUser.js
import React, { Component } from 'react';
import axios from 'axios';

class RegisterUser extends Component {
    constructor(props) {
        super(props)
        this.state = {
            username: '',
            email: '',
            password: '',
        }
    }
    changeUsernameEventHandler = event => {
        this.setState({ username: event.target.value })
    }
    changeEmailEventHandler = event => {
        this.setState({ email: event.target.value })
    }
    changePasswordEventHandler = event => {
        this.setState({ password: event.target.value })
    }
    register = event => {
        event.preventDefault()
        axios.post('http://localhost:8000/users/register', this.state, { withCredentials: true })
            .then(response => {
                if (response.data.success) {
                    console.log('User successfully registered.')
                    this.props.history.push('/login')
                }
            })
            .catch(error => {
                console.log(error)
            })
    }

    render() {
        return (
            <React.Fragment>
                <h1>Register User</h1>
                <form onSubmit={this.register}>
                    <div className="form-group">
                        <label htmlFor="username">Username</label>
                        <input type="text" id="username" className="form-control" placeholder="Enter username" autoComplete="off" value={this.state.username} onChange={this.changeUsernameEventHandler} />
                    </div>
                    <div className="form-group">
                        <label htmlFor="email">Email address</label>
                        <input type="email" id="email" className="form-control" placeholder="Enter email" autoComplete="off" value={this.state.email} onChange={this.changeEmailEventHandler} />
                        <small id="emailHelp" className="form-text text-muted">We'll never share your email with anyone else.</small>
                    </div>
                    <div className="form-group">
                        <label htmlFor="password">Password</label>
                        <input type="password" id="password" className="form-control" placeholder="Password" autoComplete="off" value={this.state.password} onChange={this.changePasswordEventHandler} />
                    </div>
                    <button type="submit" className="btn btn-primary">Submit</button>
                </form>
            </React.Fragment>

        );
    }
}

export default RegisterUser;

// front-end-angular/src/app/components/register-user/register-user.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { UserService } from '../../user.service'

@Component({
  selector: 'app-register-user',
  templateUrl: './register-user.component.html',
  styleUrls: ['./register-user.component.css']
})
export class RegisterUserComponent implements OnInit {

  constructor(
    private _Router: Router, private _UserService: UserService) { }

  ngOnInit() {
  }

  registerUser(event) {
    const target = event.target
    const username = target.querySelector('#username').value
    const email = target.querySelector('#email').value
    const password = target.querySelector('#password').value
    let data = {
      'username': username,
      'email': email,
      'password': password,
    }
    this._UserService.registerUser(data).subscribe(data => {
      if (data.success) {
        this._Router.navigate(['login'])
      } else {
        window.alert('Could not register.')
      }
    })
  }

}

<h1>Register User</h1>
<form (submit)=registerUser($event)>
    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" aria-describedby="emailHelp" placeholder="Enter username">
    </div>
    <div class="form-group">
        <label for="email">Email address</label>
        <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
