// front-end-react/src/components/Login.js
import React from 'react';

function Login() {
    return (
        <div>
            <h1>Login</h1>
            <form>
                <div className="form-group">
                    <label htmlFor="email">Email address</label>
                    <input type="email" className="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email" />
                    <small id="emailHelp" className="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div className="form-group">
                    <label htmlFor="password">Password</label>
                    <input type="password" className="form-control" id="password" placeholder="Password" />
                </div>
                <div className="form-check">
                    <input type="checkbox" className="form-check-input" id="rememberMe" />
                    <label className="form-check-label" htmlFor="rememberMe">Remember Me</label>
                </div>
                <button type="submit" className="btn btn-primary">Submit</button>
            </form>
        </div>
    );
}

export default Login;

// front-end/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { UserService } from '../../user.service'

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  constructor(
    private _Router: Router,
    private _UserService: UserService) { }

  ngOnInit() {
  }

  loginUser(event) {

    const target = event.target
    const email = target.querySelector('#email').value
    const password = target.querySelector('#password').value
    const remember = target.querySelector('#rememberMe').checked

    let data = {
      'email': email,
      'password': password,
      'remember': remember
    }

    this._UserService.loginUser(data).subscribe(data => {
      if (data.success) {
        this._UserService.setLoginStatus(true)
        this._Router.navigate(['apps'])
      } else {
        window.alert('Could not login.')
      }
    })
  }
}

<h1>Login</h1>
<form (submit)=loginUser($event)>
  <div class="form-group">
    <label for="email">Email address</label>
    <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" id="password" placeholder="Password">
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="rememberMe">
    <label class="form-check-label" for="rememberMe">Remember Me</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
