// front-end-react/src/components/Thermostats.js
import React, { Component } from 'react';
import { Link, withRouter } from 'react-router-dom'
import axios from 'axios';


class Thermostats extends Component {
    constructor(props) {
        super(props)
        this.state = {
            dataLoaded: false,
            thermostats: [],
            errMessage: ''
        }
    }

    componentDidMount() {
        axios.get('http://localhost:5000/getUserThermostats', { withCredentials: true })
            .then(response => {
                this.setState({
                    thermostats: response.data,
                    dataLoaded: true
                })
            })
            .catch(error => {
                console.log(error)
                this.setState({ errMessage: 'Error retreiving data.' })
            });
    }

    render() {
        const { dataLoaded, thermostats, errMessage } = this.state
        return (
            <div>
                {dataLoaded &&
                    <div className='row'>
                        <h1 className='col-12'> Thermostats</h1 >
                        {
                            errMessage ? <div className='col-12'>{errMessage}</div> : null
                        }
                        {
                            thermostats.length ?
                                thermostats.map(thermostat =>
                                    <div key={thermostat.api_key} className='col-12 mt-3 mb-3 app'>
                                        <div className='card bg-dark'>
                                            <div className='card-body'>
                                                <h2 className='d-inline'>{thermostat.data.name}</h2>
                                                <div className='float-right'>
                                                    <Link to='/' className='btn btn-info'>View</Link>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                ) :
                                <div className='col-12 mt-3 mb-3'>
                                    You currently have no thermostats registered with this account.
                        </div>
                        }
                    </div>
                }
            </div>

        );
    }
}

export default withRouter(Thermostats);

// front-end-angular/src/app/components/thermostats/thermostats.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { AppService } from '../../app.service';
import { Thermostat } from '../../../../app'

@Component({
  selector: 'app-thermostats',
  templateUrl: './thermostats.component.html',
  styleUrls: ['./thermostats.component.css']
})

export class ThermostatsComponent implements OnInit {

  public all_data_fetched = false;
  public thermostats = [];
  public key: string;

  constructor(
    private _Route: ActivatedRoute,
    private _AppService: AppService
  ) { }

  ngOnInit() {
    let key = this._Route.snapshot.paramMap.get('key')
    if (key) {
      this.getAppThermostats(key)
    }
    else {
      this.getUserThermostats()
    }
  }

  getAppThermostats(key: string) {
    this._AppService.getAppThermostats(key)
      .subscribe(data => {
        this.setData(data)
      });
  }

  getUserThermostats() {
    this._AppService.getUserThermostats()
      .subscribe(data => {
        this.setData(data)
      });
  }

  setData(data: Thermostat[]) {
    this.thermostats = data;
    this.all_data_fetched = true;
  }

}

<div *ngIf=all_data_fetched>
    <h1>Thermostats</h1>
    <div class='row'>
        <div class='col-12 mt-3 mb-3 app' *ngFor='let thermostat of thermostats'>
            <div class='card bg-dark'>
                <div class='card-body'>
                    <h2 class='d-inline'>{{thermostat.data.name}}</h2>
                    <div class='float-right'>
                        <a href='thermostats/{{thermostat.api_key}}/{{thermostat.data.identifier}}'
                            class='btn btn-info'>View</a>
                    </div>
                </div>
            </div>
        </div>
        <div class='col-12 mt-3 mb-3' *ngIf='!thermostats.length'>
            You currently have no thermostats or registered apps with this account.<br />
            <a href='apps/register'>Click here</a>
            to
            register your Ecobee products.
        </div>
    </div>
</div>
