// front-end-angular/src/app/components/apps/apps.component.ts
import { Component, OnInit } from '@angular/core';
import { AppService } from '../../app.service'
import { Router } from '@angular/router';
import { UserService } from '../../user.service'

@Component({
  selector: 'app-apps',
  templateUrl: './apps.component.html',
  styleUrls: ['./apps.component.css']
})
export class AppsComponent implements OnInit {

  public apps = [];
  public authorizationCode: string;

  constructor(
    private _AppService: AppService,
    private _router: Router,
    private _UserService: UserService
  ) { }

  ngOnInit() {
    if (this._UserService.loginStatus) {
      this.fetchApps();
    }
  }

  fetchApps() {
    this._AppService.getApps()
      .subscribe(data => {
        this.apps = data;
      })
  }

  onSelect() {
    this._router.navigate(['/apps/thermostats'])
  }

  deleteApp(key: string) {
    this._AppService.deleteApp(key)
      .subscribe(r => {
        console.log(r)
        this.fetchApps()
      });
  }

  reAuthorizeApp(key: string) {
    this._AppService.authorizeApp(key).
      subscribe(response => {
        this.authorizationCode = response.data.authorization_code
        alert(response.data.pin)
      })
  }

  updateAppCredentials(key: string) {
    if (this.authorizationCode) {
      this._AppService.updateAppCredentials(key, this.authorizationCode).subscribe(response => {
        if (response.success) {
          alert('updated')
          this.fetchApps();
        }
        else {
          alert('Failed to reauthorize, try again.')
        }
      })

    }
    else {
      alert('Reauthorize App first.')
    }

  }
}

<div class='row'>
    <h1 class='col-6'>Apps</h1>
    <div class='col-6'>
        <a class='btn btn-primary btn-lg float-right' routerLink='/apps/register'>Register App</a>
    </div>
</div>
<div class='row'>
    <div class='col-12 mt-3 mb-3 app' *ngFor='let app of apps'>
        <div class='card bg-dark'>
            <div class='card-body'>
                <h2 class='d-inline'>{{app.name}}</h2>
                <div class='float-right'>
                    <a (click)='onSelect()' class='btn btn-info'>View</a>
                    <a (click)='reAuthorizeApp(app.key)' class='btn btn-info'>Reauthorize</a>
                    <a (click)='updateAppCredentials(app.key)' class='btn btn-info'>Update App Credentials</a>
                    <button (click)='deleteApp(app.key)' class='btn btn-danger'>Delete</button>
                </div>
            </div>
        </div>
    </div>
    <div class='col-12 mt-3 mb-3' *ngIf='!apps.length'>
        You currently have no apps registered with this account.
    </div>
</div>

// front-end-react/src/components/Apps.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom'
import axios from 'axios';

class Apps extends Component {
    constructor(props) {
        super(props)
        this.state = {
            apps: [],
            errMessage: ''
        }
    }

    componentDidMount() {
        axios.get('http://localhost:5000/apps', { withCredentials: true })
            .then(response => {
                this.setState({ apps: response.data })
            })
            .catch(error => {
                console.log(error)
                this.setState({ errMessage: 'Error retreiving data.' })
            });
    }

    render() {
        const { apps, errMessage } = this.state
        return (
            <div>
                <div className='row'>
                    <h1 className='col-6'>Apps</h1>
                    <div className='col-6'>
                        <Link to='blank' className='btn btn-primary btn-lg float-right'>Register App</Link>
                    </div>
                    {
                        errMessage ? <div className='col-12'>{errMessage}</div> : null
                    }
                    {
                        apps.length ?
                            apps.map(app =>
                                <div key={app.key} className='col-12 mt-3 mb-3 app'>
                                    <div className='card bg-dark'>
                                        <div className='card-body'>
                                            <h2 className='d-inline'>{app.name}</h2>
                                            <div className='float-right'>
                                                <Link to='thermostats' className='btn btn-info'>View</Link>
                                                <Link to='blank' className='btn btn-info'>Reauthorize</Link>
                                                <Link to='blank' className='btn btn-info'>Update App Credentials</Link>
                                                <button className='btn btn-danger'>Delete</button>
                                            </div>
                                        </div>
                                    </div>
                                </div >
                            ) :
                            <div className='col-12 mt-3 mb-3'>
                                You currently have no apps registered with this account.
                        </div>

                    }
                </div>

            </div >

        );
    }
}

export default Apps;
