// front-end-angular/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { FormBuilder, Validators } from '@angular/forms'
import { UserService } from '../../user.service'

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  constructor(private _FormBuilder: FormBuilder,
    private _Router: Router,
    private _UserService: UserService
  ) { }

  public loginForm = this._FormBuilder.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required]],
    remember: [null, [Validators.required]]
  })

  ngOnInit() { }

  loginUser() {
    let data = this.loginForm.value
    this._UserService.loginUser(data).subscribe(data => {
      if (data.success) {
        this._UserService.setLoginStatus(true)
        this._Router.navigate(['apps'])
      } else {
        window.alert('Could not login.')
      }
    })
  }

  get email() {
    return this.loginForm.get('email')
  }

  get password() {
    return this.loginForm.get('password')
  }

}

<h1>Login</h1>
<form [formGroup]="loginForm" (ngSubmit)=loginUser()>
  <div class="form-group">
    <label for="email">Email address</label>
    <input type="email" id="email" class="form-control" placeholder="Enter email" autocomplete="off"
      formControlName='email' [class.is-invalid]="email.invalid && email.touched">
    <div *ngIf="email.invalid && email.touched">
      <small class="text-danger" *ngIf="email.errors?.required">Email is required.</small>
      <small class="text-danger" *ngIf="email.errors?.email">Email is invalid.</small>
    </div>
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" id="password" class="form-control" placeholder="Password" formControlName='password'
      [class.is-invalid]="password.invalid && password.touched">
    <div *ngIf="password.invalid && password.touched">
      <small *ngIf="password.errors?.required" class="text-danger">Password is required.</small>
    </div>
  </div>
  <div class="form-check">
    <input type="checkbox" id='rememberMe' class="form-check-input" formControlName='remember'>
    <label class="form-check-label" for="rememberMe">Remember Me</label>
  </div>
  <button type="submit" class="btn btn-primary mt-2">Submit</button>
</form>

// front-end-react/src/components/Login.js
import React, { Component } from 'react';
import { withRouter } from 'react-router-dom'

class Login extends Component {
    constructor(props) {
        super(props)
        this.loginUser = this.loginUser.bind(this)
        this.state = {
            email: '',
            password: '',
            remember: false
        }
    }

    changeEmailEventHandler = (event) => {
        this.setState({ email: event.target.value })
    }

    changePasswordEventHandler = (event) => {
        this.setState({ password: event.target.value })
    }

    changeRememberMeEventHandler = (event) => {
        this.setState({ remember: event.target.checked });
    }

    loginUser = event => {
        event.preventDefault()
        this.props.login(this.state, () =>
            this.props.history.push('/'))
    }

    render() {
        return (
            <React.Fragment>
                <h1>Login</h1>
                <form onSubmit={this.loginUser}>
                    <div className="form-group">
                        <label htmlFor="email">Email address</label>
                        <input type="email" id="email" className="form-control" placeholder="Enter email" autoComplete="off" value={this.state.username} onChange={this.changeEmailEventHandler} />
                        <small id="emailHelp" className="form-text text-muted">We'll never share your email with anyone else.</small>
                    </div>
                    <div className="form-group">
                        <label htmlFor="password">Password</label>
                        <input type="password" id="password" className="form-control" placeholder="Password" autoComplete="off" value={this.state.password} onChange={this.changePasswordEventHandler} />
                    </div>
                    <div className="form-check">
                        <input type="checkbox" id="rememberMe" className="form-check-input" checked={this.state.rememberMe} onChange={this.changeRememberMeEventHandler} />
                        <label className="form-check-label" htmlFor="rememberMe">Remember Me</label>
                    </div>
                    <button type="submit" className="btn btn-primary">Submit</button>
                </form>
            </React.Fragment>
        )
    };
}

export default withRouter(Login);
