// front-end-angular/src/app/components/register-app/register-app.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms'
import { AppService } from '../../app.service'
import { Router } from '@angular/router';

declare var $: any;

@Component({
  selector: 'app-register-app',
  templateUrl: './register-app.component.html',
  styleUrls: ['./register-app.component.css']
})
export class RegisterAppComponent implements OnInit {

  constructor(
    private _FormBuilder: FormBuilder,
    private _AppService: AppService,
    private _router: Router
  ) { }

  public nameMinLength = 4;
  public keyLength = 32;
  public authorizationCodeLength = 32;

  public authorizeForm = this._FormBuilder.group({
    key: ['', [Validators.required, Validators.minLength(this.keyLength), Validators.maxLength(this.keyLength)]]
  })
  public pin: string;
  public registerForm = this._FormBuilder.group({
    key: [''],
    name: ['', [Validators.required, Validators.minLength(this.nameMinLength)]],
    authorizationCode: [''],
  })

  ngOnInit() { }

  authorizeApp() {
    this._AppService.authorizeApp(this.authorizeForm.value.key)
      .subscribe(response => {
        if (response.success) {
          console.log('Successfully authorized app.')
          this.pin = response.data.pin
          this.registerForm.patchValue({ key: this.authorizeForm.value.key, authorizationCode: response.data.authorization_code })
          $('#exampleModal').modal('toggle')
        }
        else {
          console.log('Could not successfully authorize app.')
        }
      });
  }

  registerApp() {
    this._AppService.createApp(this.registerForm.value)
      .subscribe(response => {
        if (response.success) {
          console.log('Successfully registered app.')
          $('#exampleModal').modal('toggle')
          this._router.navigate(['/apps'])
        }
        else {
          alert('Could not register app.')
        }
      });
  }

  get key() {
    return this.authorizeForm.get('key')
  }

  get name() {
    return this.registerForm.get('name')
  }


}

<h1>Register App</h1>
<h4>Step 1: <a href="https://www.ecobee.com/home/ecobeeLogin.jsp" target="_blank">Login to Ecobee</a></h4>
<h4>Step 2: Navigate: Account Menu > Developer</h4>
<h4>Step 3: Create New App with Ecobee Pin Authentication</h4>
<h4>Step 4: Enter the API Key provided from the App below and click Authorize App</h4>
<form class="mt-3" [formGroup]="authorizeForm" (ngSubmit)='authorizeApp()'>
    <div class='row'>
        <div class='col-12 col-md-6'>
            <div class="form-group row">
                <label for="key" class="col-12 col-md-4 col-form-label">API Key</label>
                <div class="col-12 col-md-8">
                    <input type="text" name='key' id='key' class="form-control" placeholder="Enter API Key"
                        formControlName="key" [class.is-invalid]='key.invalid && key.touched'>
                    <div *ngIf="key.invalid && key.touched">
                        <small class="text-danger" *ngIf="key.errors?.required">Password is required.</small>
                        <small class="text-danger" *ngIf="key.errors?.minlength || key.errors?.maxlength">Password must
                            be {{keyLength}} characters long.</small>
                    </div>
                </div>
            </div>
            <input type="hidden" name="authorizationCode">
        </div>
    </div>
    <button type='submit' class="btn btn-primary mb-2" [class.disabled]='key.invalid'>Authorize
        App
    </button>
</form>

<!-- Modal -->
<div class="modal fade text-dark" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Register App Form</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Instructions</h5>
                <p>
                    From the Ecobee Page <br />
                    Navigate: Account Menu > My Apps <br />
                    Click Add Application and use the pin below to validate the application.
                </p>
                <h5>Pin: {{pin}}</h5>
                <p>
                    Finally, enter a name for your App that you would like to refer to it as. For example, if it is the
                    App
                    for your home thermostat you may put 'Home' as the name or even your address.
                </p>
                <form id='registerForm' [formGroup]="registerForm" (ngSubmit)="registerApp()">
                    <div class="form-group">
                        <label for="name" class="col-form-label">App Name:</label>
                        <input type="text" id="name" class="form-control" placeholder="Enter App Name"
                            autocomplete="off" formControlName='name' [class.is-invalid]="name.invalid && name.touched">
                        <div *ngIf="name.invalid && name.touched">
                            <small class="text-danger" *ngIf="name.errors?.required">Name is required.</small>
                            <small class="text-danger" *ngIf="name.errors?.minlength">name must be at least
                                {{nameMinLength}} characters
                                long.</small>
                        </div>
                        <input type="hidden" formControlName='key'>
                        <input type="hidden" formControlName='authorizationCode'>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" form='registerForm'>Register
                    App</button>
            </div>
        </div>
    </div>
</div>

// front-end-react/src/components/RegisterApp.js
import React, { Component } from 'react';
import axios from 'axios';
import $ from 'jquery';

class RegisterApp extends Component {

    onMove = () => {
        console.log(this.testVarible);
    }

    constructor(props) {
        super(props)
        this.state = {
            key: '',
            name: '',
            pin: '',
            authorizationCode: '',

        }
    }

    changeKeyEventHandler = event => {
        this.setState({ key: event.target.value })
    }

    changeNameEventHandler = event => {
        this.setState({ name: event.target.value })
    }

    authorizeApp = event => {
        event.preventDefault()
        axios.get(`http://localhost:8000/apps/authorize/${this.state.key}`, { withCredentials: true })
            .then(response => {
                if (response.data.success) {
                    console.log('Successfully authorized app.')
                    this.setState({
                        pin: response.data.data.pin,
                        authorizationCode: response.data.data.authorization_code
                    })
                    $('#exampleModal').modal('toggle')
                }
            })
            .catch(error => {
                console.log(error)
            })
    }

    registerApp = event => {
        event.preventDefault()
        console.log(this.state)
        axios.post('http://localhost:8000/apps/create', this.state, { withCredentials: true })
            .then(response => {
                if (response.data.success) {
                    console.log('App successfully registered.')
                    $('#exampleModal').modal('toggle')
                    this.props.history.push('/apps')
                }
            })
            .catch(error => {
                console.log(error)
            })
    }

    render() {
        return (
            <React.Fragment>
                <h1>Register App</h1>
                <h4>Step 1: <a href="https://www.ecobee.com/home/ecobeeLogin.jsp" target="_blank" rel="noopener noreferrer">Login to Ecobee</a></h4>
                <h4>Step 2: Navigate: Account Menu > Developer</h4>
                <h4>Step 3: Create New App with Ecobee Pin Authentication</h4>
                <h4>Step 4: Enter the API Key provided from the App below and click Authorize App</h4>
                <form className="mt-3" onSubmit={this.authorizeApp}>
                    <div className='row'>
                        <div className='col-12 col-md-6'>
                            <div className="form-group row">
                                <label htmlFor="key" className="col-12 col-md-4 col-form-label">API Key</label>
                                <div className="col-12 col-md-8">
                                    <div>
                                        <input type="text" name='key' id='key' className="form-control" placeholder="Enter API Key" /*autoComplete="off"*/ value={this.state.key} onChange={this.changeKeyEventHandler} />
                                        {/* <small className="text-danger">Key is required.</small>
                                        <small className="text-danger">Key must be {this.props.keyLength} characters long.</small> */}
                                    </div>
                                </div>
                            </div>
                            <input type="hidden" name="authorizationCode" />
                        </div>
                    </div >
                    <button type='submit' className="btn btn-primary mb-2">Authorize App</button >
                </form >

                <div className="modal fade text-dark" id="exampleModal" tabIndex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div className="modal-dialog" role="document">
                        <div className="modal-content">
                            <div className="modal-header">
                                <h5 className="modal-title" id="exampleModalLabel">Register App Form</h5>
                                <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div className="modal-body">
                                <h5>Instructions</h5>
                                <p>
                                    From the Ecobee Page <br />
                                    Navigate: Account Menu > My Apps <br />
                                    Click Add Application and use the pin below to validate the application.
                                    </p>
                                <h5>Pin: {this.state.pin}</h5>
                                <p>
                                    Finally, enter a name for your App that you would like to refer to it as. For example, if it is the
                                    App
                                    for your home thermostat you may put 'Home' as the name or even your address.
                </p>
                                <form id='registerForm' onSubmit={this.registerApp}>
                                    <div className="form-group">
                                        <label htmlFor="name" className="col-form-label">App Name:</label>
                                        <input type="text" id="name" className="form-control" placeholder="Enter App Name" autoComplete="off" value={this.state.name} onChange={this.changeNameEventHandler} />
                                        {/* <div>
                                            <small className="text-danger">Name is required.</small>
                                            <small className="text-danger" >name must be at least
                            nameminlength characters
                                long.</small>
                                        </div> */}
                                    </div>
                                </form>
                            </div>
                            <div className="modal-footer">
                                <button type="button" className="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" className="btn btn-primary" form='registerForm'>Register
                    App</button>
                            </div>
                        </div>
                    </div>
                </div >
            </React.Fragment >

        );
    }
}

export default RegisterApp;
