// front-end/src/app/components/thermostats/thermostats.component.ts
import { Component, OnInit } from '@angular/core';
import { APIService } from '../../api.service'

@Component({
    selector: 'app-thermostats',
    templateUrl: './thermostats.component.html',
    styleUrls: ['./thermostats.component.css']
})
export class ThermostatsComponent implements OnInit {

    public thermostats = [];

    constructor(private _APIService: APIService) { }

    ngOnInit() {
        this._APIService.getThermostats()
        .subscribe(data => this.thermostats = data);
    }

}

<h1>Thermostats</h1>
<div class='row'>
    <div class='col-12 mt-3 mb-3 app' *ngFor='let thermostat of thermostats'>
        <div class='card bg-dark'>
            <div class='card-body'>
                <h2 class='d-inline'>{{thermostat.name}}</h2>
                <div class='float-right'>
                    <a routerLink='/thermostat' class='btn btn-info'>View</a>
                </div>
            </div>
        </div>
    </div>
</div>

// front-end-react/src/components/Thermostats.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom'
import axios from 'axios';


class Thermostats extends Component {
    constructor(props) {
        super(props)
        this.state = {
            thermostats: [],
            errMessage: ''
        }
    }

    componentDidMount() {
        axios.get('http://localhost:5000/getUserThermostats', { withCredentials: true })
            .then(response => {
                this.setState({ thermostats: response.data })
            })
            .catch(error => {
                console.log(error)
                this.setState({ errMessage: 'Error retreiving data.' })
            });
    }

    render() {
        const { thermostats, errMessage } = this.state
        return (
            <div>
                <div className='row'>
                    <h1 className='col-12'> Thermostats</h1 >
                    {
                        errMessage ? <div className='col-12'>{errMessage}</div> : null
                    }
                    {
                        thermostats.length ?
                            thermostats.map(thermostat =>
                                <div className='col-12 mt-3 mb-3 app'>
                                    <div className='card bg-dark'>
                                        <div className='card-body'>
                                            <h2 className='d-inline'>{thermostat.data.name}</h2>
                                            <div className='float-right'>
                                                <Link to='/' className='btn btn-info'>View</Link>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            ) :
                            <div className='col-12 mt-3 mb-3'>
                                You currently have no thermostats registered with this account.
                        </div>
                    }
                </div>
            </div>
        );
    }
}

export default Thermostats;
